# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Container Apps
parameters:
  - name: param
    type: object
    default: ["a","b","c","d","e"]

jobs:
- job: test
  steps:
    - task: CmdLine@2
      inputs:
        script: |
        
          # Update the list of packages
          apt-get update
          
          # Install pre-requisite packages.
          apt-get install -y wget apt-transport-https software-properties-common

          # Download the Microsoft repository GPG keys
          wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

          # Register the Microsoft repository GPG keys
          dpkg -i packages-microsoft-prod.deb

          # Update the list of packages after we added packages.microsoft.com
          apt-get update

          # Install PowerShell
          apt-get install -y powershell
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $username = 'dhr.prins@gmail.com'

          function Get-BasicAuthCreds {
            param([string]$Username,[string]$Password)
            $AuthString = "{0}:{1}" -f $Username,$Password
            $AuthBytes  = [System.Text.Encoding]::Ascii.GetBytes($AuthString)
            return [Convert]::ToBase64String($AuthBytes)
          }
          $BasicCreds = Get-BasicAuthCreds -Username $username -Password $(GithubPat)

          git clone --mirror https://$BasicCreds@github.com/dylansitblog/ITScripts.git
          cd ITScripts.git
          git push --mirror https://$env:SYSTEM_ACCESSTOKEN@dev.azure.com/dylansitblog/boards/_git/SemVerContainer
        pwsh: true
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    