# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# pool: Container Apps
parameters:
  - name: param
    type: object
    default: ["a","b","c","d","e"]

jobs:
- job: test
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $ git clone --mirror https://github.com/dylansitblog/SemVerContainer.git
          $ cd upstream-repository.git
          $ git push --mirror https://dev.azure.com/dylansitblog/boards/_git/SemVerContainer
      env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)